### ISSUE TITLE
Yearn staking

### ISSUE THREAD

**Issue by lsqrl** [Aleph-finance/aleph#101]
Three staking opportunities:
- [ ]  Vault's native coins. Only part of these ones should be staked, since they are needed to feed the margin trading.
- [x]  Vault's shadow liquidity. This can be staked entirely, although it poses a problem to earning distribution: if we choose to also swap the margin, we should distribute the earnings both to the vault and to the trader (properly weighted). Notice that the earnings are in a spurious token, therefore need to be swapped. Liquidations event and position data display should _not_ be affected by the earnings.

**Comment by grcasanova** [comment]
Calculate trader payback for profits and losses
